//
// Created by umnik on 23.09.2026.
//

#ifndef FM_V3_DIAGNOSTIC_TASK_H
#define FM_V3_DIAGNOSTIC_TASK_H

#define DIAGNOSTIC_NETWORK_TASK_PORT 1428
#define DIAGNOSTIC_NETWORK_TASK_INTERVAL_MS 1000
#define DIAGNOSTIC_NETWORK_SEND_TIMEOUT_MS 500
#define DIAGNOSTIC_TASK_STACK_SIZE_BYTES (1024U * 4U)

void DiagnosticTask(void *argument);

#endif // FM_V3_DIAGNOSTIC_TASK_H
